
github: MissAri1
patreon: #
open_collective: #
ko_fi: #
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
lfx_crowdfunding: #
polar: #
buy_me_a_coffee: MissAri1
thanks_dev: MissAri1
custom: 
